# Site settings
author: Carson Sievert
title: Approximately Normal
email: cpsievert1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A reproducible gallery of statistical graphics and computation
url: "http://cpsievert.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:title.html
exclude: ["animint/", "elife/"]

# Build settings
markdown: kramdown
